/**
 * OOPSBannerApp UC2 - Banner Display Application
 * 
 * This class demonstrates the creation of a visual banner displaying the word "OOPS" 
 * uding ASCII art composed of asterisks (*) and spaces. The banner is printed to the 
 * console using induvidual print statements for each line, creating a decorative 
 * text effect.
 * 
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O,O,O and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output
 * </p>
 * 
 * @author Developer
 * @version 2
 */
// Extend the user story 1 to display the message "OOPS" in a banner format
// using characters formed by spaces and asterisks (*) to create a visual 
// effect for each letter in the message. Use print statements for each line
// instead of a loop.

public class PrintBannerApp {
    // Main method to run the banner display
    // Print each line of the OOPS banner to create the visual effect for the
    // message "OOPS". Construct each line using string concatenation.
    // Each lime corresponds to a row in the banner for the letters O,O,P,S.
    // Using induvidual print statements for each line.
    public static void main(String[] args){
        Banner banner= new Banner();
        banner.display();
    }
}
class Banner{
    public void display() {

        System.out.println("  ***       ***    ******        ***** ");
        System.out.println("**   **   **   **  **    **    **    ");
        System.out.println("**   **   **   **  **     ** **    ");
        System.out.println("**   **   **   **  **    **   ***");
        System.out.println("**   **   **   **  ******         **");
        System.out.println("**   **   **   **  **              **");
        System.out.println("**   **   **   **  **             ** ");
        System.out.println("  ***       ***    **        ***** ");
        
    }
    
}